"use strict";

module.exports = {

	INVALID_CREDENTIALS: 101,
	DUPLICATE_USERNAME: 102,
	DUPLICATE_EMAIL: 103,
	PASSWORD_VERIFICATION_FAILED: 104,
	EMAIL_NOT_VERIFIED: 105,
	INVALID_EMAIL_VERIFY_KEY: 106,
	INVALID_EMAIL: 107,

	VALIDATION_FAILED: 200,


	INVALID_ID: 201,
	ALREADY_LIKED: 230,
	NEVER_LIKED: 231,
	ALREADY_UNLIKED: 232,
	POST_EDIT_TIME_EXPIRED: 233,

	REQUEST_ALREADY_EXISTS: 241,

    INVALID_SNAPSHOTS_TOKEN: 400,
    MISSING_SNAPSHOTS_PATH: 401,

	MULTIPLE_FILES: 301,
	NO_FILES_FOUND: 302,
	MISSING_QUERY_PARAMS: 303,


	INTERNAL_SERVER_ERROR: 500,


	//ADMIN ERRORS

	DUPLICATE_LANGUAGE: 701,
	DUPLICATE_TRANSLATION_GROUP: 702,
	ADDING_TRANSLATION_KEY_NOT_ALLOWED: 703,
	DELETING_DEF_LANGUAGE_NOT_ALLOWED: 704,
	DUPLICATE_MATERIAL_NAME: 705

};